name: Apptainer Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-container:
    runs-on: geant-gha-runner
    permissions:
      contents: read
      packages: write

    container:
      image: carlomt/apptainer:1.3.2
      options: --privileged

    name: Build and Deploy Container
    steps:

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set build tag
        id: set_tag
        run: |
          echo "tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Set SIF filename
        id: set_sif
        run: |
          sif_file=$(echo "${{ github.repository }}" | awk -F/ '{print $2}')  # estrae solo "LowEFrag"
          echo "sif=${sif_file}.sif" >> $GITHUB_OUTPUT

      - name: Build Container
        run: |
          apptainer build ${{ steps.set_sif.outputs.sif }} Apptainer.def

      - name: Login to GHCR
        run: |
          echo ${{ secrets.GHCR_PAT }} | apptainer registry login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io

      - name: Push Container to GHCR
        run: |
          repo_lower=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "Pushing to: oras://ghcr.io/${repo_lower}:${{ steps.set_tag.outputs.tag }}"
          apptainer push ${{ steps.set_sif.outputs.sif }} oras://ghcr.io/${repo_lower}:${{ steps.set_tag.outputs.tag }}
          
