name: Container unit test

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Apptainer Build and Deploy"]
    types:
      - completed

jobs:
  pull-and-run-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    container:
      image: carlomt/apptainer:1.3.2
      options: --privileged

    name: Pull and Run Container
    steps:

      - name: Set tag and repo lowercase
        id: setup
        run: |
          TAG=${{ github.event.workflow_run.head_sha }}
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          echo "repo_lower=$REPO_LOWER" >> $GITHUB_OUTPUT

      - name: Set SIF filename
        id: set_sif
        run: |
          sif_file=$(echo "${{ github.repository }}" | awk -F/ '{print $2}')  
          echo "sif=${sif_file}.sif" >> $GITHUB_OUTPUT

      - name: Checkout repository
        uses: actions/checkout@v4          
          
      - name: Login to GHCR
        run: |
          echo ${{ secrets.GHCR_PAT }} | apptainer registry login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io

      - name: Pull Container from GHCR
        run: |
          apptainer pull ${{ steps.set_sif.outputs.sif }} \
          oras://ghcr.io/${{ steps.setup.outputs.repo_lower }}:${{ steps.setup.outputs.tag }}

      - name: Restore Geant4 data from cache
        id: g4data-cache
        uses: actions/cache@v4
        with:
          path: /tmp/g4data
          key: geant4-data-v1

      - name: Download Geant4 data libraries (if cache miss) using geant4-config
        if: steps.g4data-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p /tmp/g4data
          apptainer exec --unsquash -B /tmp/g4data:/g4data \
          ${{ steps.set_sif.outputs.sif }} \
          bash -c "geant4-config --install-datasets"

      - name: List contents of /tmp/g4data
        run: |
          ls -lh /tmp/g4data
          
      - name: List contents of /g4data
        run: |
          apptainer exec \
          --unsquash \
          -B /tmp/g4data:/g4data:ro \
          ${{ steps.set_sif.outputs.sif }} \
          bash -c "ls /g4data"

      - name: Check Geant4 datasets (fail if any NOTFOUND)
        run: |
          echo "Checking Geant4 datasets..."
          OUTPUT=$(apptainer exec \
          --unsquash \
          -B /tmp/g4data:/g4data:ro \
          ${{ steps.set_sif.outputs.sif }} \
          bash -c "geant4-config --check-datasets")

          echo "$OUTPUT"

          if echo "$OUTPUT" | grep -q NOTFOUND; then
           echo "‚ùå ERROR: One or more required Geant4 datasets are missing."
           echo "$OUTPUT" | grep NOTFOUND
           exit 1          
          fi
          
      - name: Run the container
        run: |
          echo "Running container..."
          apptainer run \
          --unsquash \
          -B /tmp/g4data:/g4data:ro \
          ${{ steps.set_sif.outputs.sif }} \
          $GITHUB_WORKSPACE/macro/unit.mac


